---

- name: copy prometheus
  copy: src=prometheus dest=/tmp

- name: Get current namespaces
  command: kubectl get namespaces -o go-template={% raw %}'{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'{% endraw %}
  register: k8s_namespaces
  changed_when: false

- name: Create namespace
  command: kubectl create namespace {{ prom_deploy.namespace }}
  when: prom_deploy.namespace not in k8s_namespaces.stdout_lines

- name: copy deploy
  template: src=deploy.j2 dest={{ prom_deploy.path }}/deploy.sh  mode=0777

- name: copy teardown
  template: src=teardown.j2 dest={{ prom_deploy.path }}/teardown.sh mode=0777

- name: copy ingress
  template: src=ingress.j2 dest={{ prom_deploy.path }}/prometheus/kube-prom-ingress.yml

- name: copy alert manager
  template: src=alertmanager-config.j2 dest={{ prom_deploy.path }}/alertmanager/alertmanager-config.yml

- name: copy alert rules
  template: src=prometheus-k8s-rules.j2 dest={{ prom_deploy.path }}/prometheus/prometheus-k8s-rules.yml 
