apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ferm-celery-worker
  labels:
    k8s-app: ferm-celery-worker
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: ferm-celery-worker
  namespaceSelector:
    matchNames:
    - dev05
  endpoints:
  - port: ferm-celery-worker
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
